routes/web.php
<?php

use App\Helpers\Enums\UserRoleEnum;
use App\Http\Controllers\LanguageController;
use App\Models\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//  HOME ================================
Route::namespace('Front')->group(function (){
    Route::get('/auth/qrcode/{user:username}','QRCodeController@login')->name('auth.qrcode');
    Route::get('/auth/blocked/{user:username}','QRCodeController@blocked')->name('auth.blocked')->middleware(['auth']);
    Route::get('/check/certificate/{user:username}',function (User $user){})->name('check.certificate');
    Route::as('home.')->group(function (){

        Route::view('/', 'front.page.index')->name('index');
        Route::get('news','NewsController@index')->name('news.index');
        Route::get('news/{news:alias}','NewsController@show')->name('news.show');
        Route::get('decree','DecreeController@index')->name('decree.index');
        Route::get('decree/{decree:alias}','DecreeController@show')->name('decree.show');
        Route::get('certificate','CertificateController@index')->name('certificate.index');
        Route::post('certificate','CertificateController@search')->name('certificate.search');
        Route::get('certificate/{user:username}/download', 'CertificateController@download')->name('certificate.download');

        Route::prefix('vacancy')->as('vacancy.')->group(function (){
            Route::get('/','VacancyController@index')->name('index');
            Route::get('/{section:alias}','VacancyController@group')->name('group');
            Route::get('/{section:alias}/{vacancy:alias}','VacancyController@show')->name('show');
            Route::post('/{section:alias}/{vacancy:alias}','VacancyController@application')->name('application');
        });


    });
});

//  AUTH ================================
Auth::routes(['verify' => false]);

//  DASHBOARD ================================
Route::prefix('dashboard')
    ->namespace('Dashboard')
    ->as('dashboard.')
    ->middleware(['auth','role:'.UserRoleEnum::SUPER.'|'.UserRoleEnum::ADMIN.'|'.UserRoleEnum::MODERATOR])
    ->group(function (){
        Route::get('/','DashboardController@index')->name('index');

        //    News ======================================================================================
        Route::resource('news','NewsController')->except('show')->parameters(['news' => 'news:alias']);
        //    Decree ======================================================================================
        Route::resource('decree','DecreeController')->except('show')->parameters(['decree' => 'decree:alias']);
        //    Vacancy ======================================================================================
        Route::resource('vacancy','VacancyController')->parameters(['vacancy' => 'vacancy:alias']);

        Route::get('application','DashboardController@index')->name('vacancy.application');

        Route::prefix('group')->namespace('Group')->as('group.')->group(function (){
            Route::get("/",'GroupController@index')->name('index');

            Route::resource('section','SectionController')->except('show','edit','create');
            Route::resource('department','DepartmentController')->except('show','edit','create');
            Route::resource('position','PositionController')->except('show','edit','create');
        });

        Route::get('certificate','CertificateController@index')->name('certificate.index');
        Route::get('certificate/template','CertificateController@index')->name('certificate.template');

        Route::get('activity','DashboardController@index')->name('activity');
        Route::get('archive','DashboardController@index')->name('archive');

        Route::prefix('/staff')->namespace('Staff')->as('staff.')->group(function(){
            Route::get('/','StaffController@index')->name('index');
            Route::get('table','StaffController@table')->name('table');
            Route::get('excel','StaffController@exportExcel')->name('excel');
            Route::get('control','StaffController@control')->name('control');
            Route::get('create','ProfileController@create')->name('create');
            Route::post('create','ProfileController@store')->name('store');

            Route::prefix('{user:username}')->group(function (){
                Route::get('/','ProfileController@index')->name('profile.index');
                Route::delete('/','ProfileController@destroy')->name('profile.destroy');

                Route::put('profile','ProfileController@update')->name('profile.update');
                Route::put('profile/password/new', 'ProfileController@changePassword')->name('profile.password.new');
                Route::put('profile/password.reset', 'ProfileController@resetPassword')->name('profile.password.reset');

                Route::get('information','InformationController@index')->name('information.index');
                Route::post('information','InformationController@store')->name('information.store');
                Route::put('information','InformationController@update')->name('information.update');
                Route::delete('information','InformationController@destroy')->name('information.destroy');

                Route::get('education','EducationController@index')->name('education.index');
                Route::post('education','EducationController@store')->name('education.store');
                Route::put('education','EducationController@update')->name('education.update');
                Route::delete('education','EducationController@destroy')->name('education.destroy');

                Route::post('education/finished','EducationFinishedController@store')->name('education.finished.store');
                Route::put('education/finished/{finished}','EducationFinishedController@update')->name('education.finished.update');
                Route::delete('education/finished/{finished}','EducationFinishedController@destroy')->name('education.finished.destroy');

                Route::get('labor','LaborController@index')->name('labor.index');
                Route::post('labor','LaborController@store')->name('labor.store');
                Route::put('labor','LaborController@update')->name('labor.update');
                Route::delete('labor','LaborController@destroy')->name('labor.destroy');

                Route::get('work','WorkController@index')->name('work.index');
                Route::post('work','WorkController@store')->name('work.store');
                Route::put('work/{work}','WorkController@update')->name('work.update');
                Route::delete('work/{work}','WorkController@destroy')->name('work.destroy');

                Route::get('vacation','VacationController@index')->name('vacation.index');
                Route::post('vacation','VacationController@store')->name('vacation.store');
                Route::put('vacation/{vacation}','VacationController@update')->name('vacation.update');
                Route::delete('vacation/{vacation}','VacationController@destroy')->name('vacation.destroy');

                Route::get('family','FamilyController@index')->name('family.index');
                Route::post('family','FamilyController@store')->name('family.store');
                Route::put('family/{family}','FamilyController@update')->name('family.update');
                Route::delete('family/{family}','FamilyController@destroy')->name('family.destroy');

                Route::get('file','FileController@index')->name('file.index');
                Route::post('file','FileController@store')->name('file.store');
                Route::put('file','FileController@update')->name('file.update');
                Route::delete('file','FileController@destroy')->name('file.destroy');

                Route::get('reference', 'StaffController@reference')->name('reference');
                Route::get('certificate', 'StaffController@certificate')->name('certificate');
            });
        });
});

Route::prefix('staff-dashboard')
    ->namespace('StaffDashboard')
    ->as('staff-dashboard.')
    ->middleware(['auth','role:'.UserRoleEnum::STAFF])
    ->group(function (){
        Route::get('/','StaffDashboardController@index')->name('index');
        Route::get('reference', 'StaffController@reference')->name('staff.reference');
        Route::get('certificate', 'StaffController@certificate')->name('staff.certificate');

        Route::prefix('/pagination')->as('staff.')->namespace('Pagination')->group(function (){
            Route::get('profile','ProfileController@index')->name('profile.index');

            Route::put('profile','ProfileController@update')->name('profile.update');
            Route::put('profile/password/new', 'ProfileController@changePassword')->name('profile.password.new');

            Route::get('information','InformationController@index')->name('information.index');
            Route::post('information','InformationController@store')->name('information.store');
            Route::put('information','InformationController@update')->name('information.update');

            Route::get('education','EducationController@index')->name('education.index');
            Route::post('education','EducationController@store')->name('education.store');
            Route::put('education','EducationController@update')->name('education.update');

            Route::post('education/finished','EducationFinishedController@store')->name('education.finished.store');
            Route::put('education/finished/{finished}','EducationFinishedController@update')->name('education.finished.update');

app/Http/Controllers/Dashboard/Group/DepartmentController.php
<?php

namespace App\Http\Controllers\Dashboard\Group;

use App\DTO\DepartmentDTO;
use App\Http\Controllers\Dashboard\BaseController;
use App\Http\Requests\Dashboard\Group\DepartmentRequest;
use App\Models\Department;
use App\Models\Section;
use Exception;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;


class DepartmentController extends BaseController
{
    public function index(){
        $breadcrumbs = [
            ['link' => route('dashboard.index'), 'name' => "<i class='feather icon-home'></i>"],
            ['name' => __('page.dashboard.group.title')],
            ['name' => __('page.dashboard.group.department.title')]
        ];
        $departments = Department::query()->latest()->get();
        $sections = Section::all();
        return view('dashboard.page.group.department.index',compact('breadcrumbs','departments','sections'));
    }

    public function store(DepartmentRequest $request): RedirectResponse
    {
        $data = DepartmentDTO::fromRequest($request);
        $department = Department::create($data->toArray());
        try {
            alert()->success($department->title,__('dashboard.section_added'));
            return redirect()->route('dashboard.group.department.index');
        }catch (Exception $exception){
            alert()->error(__('dashboard.department'),__('dashboard.not_saved'));
            return redirect()->route('dashboard.group.department.index')->withInput();
        }
    }

    public function update(DepartmentRequest $request, Department $department): RedirectResponse
    {
        $data = DepartmentDTO::fromRequest($request);
        $department->update($data->toArray());
        try {
            alert()->success($department->title,__('dashboard.department_updated'));
            return redirect()->route('dashboard.group.department.index');
        }catch (Exception $exception){
            alert()->error(__('dashboard.department'),__('dashboard.not_updated'));
            return redirect()->route('dashboard.group.department.index')->withInput();
        }
    }

    public function destroy(Department $department): JsonResponse
    {
        if (request()->wantsJson()){
            try {
                $department->delete();
                return response()->json([
                    'status' => 'success',
                    'message' => [
                        'title' => __('message.deleted'),
                        'text' => __('message.model_deleted')
                    ]
                ]);
            }catch (Exception $exception){
                return response()->json([
                    'status' => 'success',
                    'message' => [
                        'title' => __('message.code_500')
                    ]
                ],500);
            }
        }
        return response()->json([
            'status' => 'success',
            'message' => [
                'title' => __('message.code_404')
            ]
        ],404);
    }
}

app/Http/Controllers/Dashboard/Group/GroupController.php
<?php


namespace App\Http\Controllers\Dashboard\Group;


use App\Http\Controllers\Dashboard\BaseController;

class GroupController extends BaseController
{

    public function index(){
        $breadcrumbs = [
            ['link' => route('dashboard.index'), 'name' => "<i class='feather icon-home'></i>"],
            ['name' => __('page.dashboard.group.title')]
        ];
        return view('dashboard.page.group.index',compact('breadcrumbs'));
    }
}

app/Http/Controllers/Dashboard/Group/PositionController.php
<?php


namespace App\Http\Controllers\Dashboard\Group;


use App\DTO\PositionDTO;
use App\Http\Controllers\Dashboard\BaseController;
use App\Http\Requests\Dashboard\Group\PositionRequest;
use App\Models\Department;
use App\Models\Position;
use Exception;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;

class PositionController extends BaseController
{
    public function index(){
        $breadcrumbs = [
            ['link' => route('dashboard.index'), 'name' => "<i class='feather icon-home'></i>"],
            ['name' => __('page.dashboard.group.title')],
            ['name' => __('page.dashboard.group.position.title')]
        ];
        $positions = Position::query()->latest()->get();
        $departments = Department::all();
        return view('dashboard.page.group.position.index',compact('breadcrumbs','departments','positions'));
    }

    public function store(PositionRequest $request): RedirectResponse
    {
        $data = PositionDTO::fromRequest($request);
        $position = Position::create($data->toArray());
        try {
            alert()->success($position->title,__('dashboard.position_added'));
            return redirect()->route('dashboard.group.position.index');
        }catch (Exception $exception){
            alert()->error(__('dashboard.position'),__('dashboard.not_saved'));
            return redirect()->route('dashboard.group.position.index')->withInput();
        }
    }

    public function update(PositionRequest $request, Position $position): RedirectResponse
    {
        $data = PositionDTO::fromRequest($request);
        $position->update($data->toArray());
        try {
            alert()->success($position->title,__('dashboard.position_updated'));
            return redirect()->route('dashboard.group.position.index');
        }catch (Exception $exception){
            alert()->error(__('dashboard.position'),__('dashboard.not_updated'));
            return redirect()->route('dashboard.group.position.index');
        }
    }
    public function destroy(Position $position): JsonResponse
    {
        if ( request()->wantsJson() ){
            try {
                $position->delete();
                return response()->json([
                    'status' => 'success',
                    'message' => [
                        'title' => __('message.deleted'),
                        'text' => __('message.model_deleted')
                    ]
                ]);
            }catch (Exception $exception){
                return response()->json([
                    'status' => 'success',
                    'message' => [
                        'title' => __('message.code_500')
                    ]
                ],500);
            }
        }
        return response()->json([
            'status' => 'success',
            'message' => [
                'title' => __('message.code_404')
            ]
        ],404);
    }





}

resources/views/dashboard/page/group/section/index.blade.php
@extends('dashboard.layouts.dashboard')

@section('title',__('page.dashboard.group.section.title'))

@section('vendor-style')
    {{-- vendor css files --}}
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/dataTables.bootstrap4.min.css')) }}">
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/responsive.bootstrap4.min.css')) }}">
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/buttons.bootstrap4.min.css')) }}">
@endsection


@section('content')
    <section id="data-list-view" class="data-list-view-header">
        <div class="card">
            <div class="card-body">
                <div class="card-content">
                    <div class="row" id="table-hover-animation">
                        <div class="col-12 text-right">
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#js__create"><i class="feather icon-plus"></i> {{ __('page.dashboard.group.section.create') }}</button>
                        </div>
                        <div class="col-12">
                            <div class="card-datatable">
                                <table class="dt-responsive table">
                                    <thead>
                                    <tr>
                                        <th></th>
                                        <th>№</th>
                                        <th>{{ __('page.dashboard.group.section.input.title') }}</th>
                                        <th>__</th>
                                        <th>{{ __('page.dashboard.group.section.input.created_at') }}</th>
                                        <th>{{ __('dashboard.action.title') }}</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @forelse ($sections as $section)
                                        <tr>
                                            <td></td>
                                            <td>{{ $section->id }}</td>
                                            <td>{{ $section->title }}</td>
                                            <td>{{ count($section->department) }}</td>
                                            <td><i class="feather icon-clock text-primary"></i> {{ $section->created_at->format('H:i d.m.Y') }}</td>
                                            <td>
                                                <button type="button"
                                                        class="btn btn-link m-0 p-0 text-primary js__edit"
                                                        data-toggle="modal"
                                                        data-target="#js__edit_{{$section->id}}"
                                                ><i class="feather icon-edit"></i></button>
                                                <button type="button"
                                                        class="btn btn-link m-0 p-1 text-danger"
                                                        onclick="js_delete('{{route('dashboard.group.section.destroy',['section' => $section->id])}}')"
                                                ><i class="feather icon-trash"></i></button>
                                            </td>
                                        </tr>
                                    @empty

                                    @endforelse
                                    </tbody>

                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="modal modal-slide-in fade" id="js__create">
        <div class="modal-dialog sidebar-sm">
            <form method="POST" action="{{ route('dashboard.group.section.store') }}" class="was-validated add-new-record modal-content pt-0">
                @csrf
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">×</button>
                <div class="modal-header mb-1">
                    <h5 class="modal-title" id="create_modal-label">{{ __('page.dashboard.group.section.create') }}</h5>
                </div>
                <div class="modal-body flex-grow-1">
                    <x-html.input :required="true" name="title" type="text" :label="__('page.dashboard.group.section.input.title')" :disabled="false"/>
                    <button type="submit" class="btn btn-primary data-submit mr-1">{{ __('dashboard.action.add') }}</button>
                    <button type="reset" class="btn btn-outline-secondary" data-dismiss="modal">{{ __('dashboard.action.cancel') }}</button>
                </div>
            </form>
        </div>
    </div>
    @foreach($sections as $section)
        <div class="modal modal-slide-in fade" id="js__edit_{{$section->id}}">
        <div class="modal-dialog sidebar-sm">
            <form class="was-validated add-new-record modal-content pt-0" action="{{ route('dashboard.group.section.update',['section' => $section->id]) }}" method="POST">
                @csrf
                @method('PUT')
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">×</button>
                <div class="modal-header mb-1">
                    <h5 class="modal-title" id="edit_modal-label-{{$section->id}}">{{ __('page.dashboard.group.section.update') }}</h5>
                </div>
                <div class="modal-body flex-grow-1">
                    <x-html.input :required="true" name="title" :value="$section->title" id-name="edit-title-{{$section->id}}" type="text" :label="__('page.dashboard.group.section.input.title')" :disabled="false"/>
                    <button type="submit" class="btn btn-primary data-submit mr-1">{{ __('dashboard.action.edit') }}</button>
                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">{{ __('dashboard.action.cancel') }}</button>
                </div>
            </form>
        </div>
    </div>
    @endforeach
@endsection

@section('vendor-script')
    {{-- vendor files --}}
    <script src="{{ asset(mix('vendors/js/tables/datatable/jquery.dataTables.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.bootstrap4.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/dataTables.responsive.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/responsive.bootstrap4.js')) }}"></script>
    <script src="{{ asset('vendor/axios/axios.min.js') }}"></script>
@endsection

@section('page-script')
    {{-- Page js files --}}
    <script>
        function js_delete(route){
            Swal.fire({
                title: '{{ __('message.are_you_sure') }}',
                text: '{{ __('message.dont_revert') }}',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: '{{ __('message.yes_delete') }}',
                cancelButtonText: '{{ __('message.cancel') }}',
                customClass: {
                    confirmButton: 'btn btn-primary',
                    cancelButton: 'btn btn-outline-danger ml-1'
                },
                buttonsStyling: false
            }).then(function (result) {
                if (result.value) {
                    axios.delete(route).then(response => {
                        let data = response.data
                        if (data.status === 'success'){
                            Swal.fire({
                                title: data.message.title,
                                text: data.message.text,
                                icon: 'success',
                                showCancelButton: false,
                                confirmButtonText: 'Ok',
                                customClass: {
                                    confirmButton: 'btn btn-primary',
                                },
                                buttonsStyling: false
                            }).then(function (result){
                                if (result.value){
                                    window.location.reload()
                                }else{

                                }
                            });
                        }
                    }).catch(response => {
                        Swal.fire({
                            icon: 'error',
                            title: '{{ __('message.deleted') }}',
                            customClass: {
                                confirmButton: 'btn btn-success'
                            }
                        });
                    })

                }
            });
        }

        $(document).ready(function (){
            $('.js__edit').on('click',function (){
                let route = $(this).data('route')
                let title = $(this).data('title')
                $('#edit-title').val(title);
                $('#js__form-edit').attr('action',route)
            });
        });



        let dt_responsive_table = $('.dt-responsive')
            let dt_responsive = dt_responsive_table.DataTable({
                pageLength: 10,
                aLengthMenu: [[5, 10, 15, 20], [5, 10, 15, 20]],
                columnDefs: [
                    {
                        className: 'control',
                        orderable: false,
                        targets: 0
                    },
                ],
                dom:
                    '<"d-flex justify-content-between align-items-center mx-0 row"<"col-sm-12 col-md-6"l><"col-sm-12 col-md-6"f>>t<"d-flex justify-content-between mx-0 row"<"col-sm-12 col-md-6"i><"col-sm-12 col-md-6"p>>',
                responsive: {
                    details: {
                        display: $.fn.dataTable.Responsive.display.modal({
                            header: function (row) {
                                var data = row.data();
                                return 'Details of ' + data['full_name'];
                            }
                        }),
                        type: 'column',
                        renderer: $.fn.dataTable.Responsive.renderer.tableAll({
                            tableClass: 'table'
                        })
                    }
                },
                language: {
                    "decimal":        "",
                    "emptyTable":     "Нет данных в таблице",
                    "info":           "Показано с _START_ по _END_ из _TOTAL_ записей",
                    "infoEmpty":      "Показано с 0 по 0 из 0 записей",
                    "infoFiltered":   "(отфильтровано из _MAX_ записей)",
                    "infoPostFix":    "",
                    "thousands":      ",",
                    "lengthMenu":     "Показать _MENU_ записей",
                    "loadingRecords": "Загрузка...",
                    "processing":     "Обработка...",
                    "search":         "Поиск:",
                    "zeroRecords":    "Совпадающих записей не найдено",
                    "paginate": {
                        "first":      "Первый",
                        "last":       "Последний",
                        previous: '&nbsp;',
                        next: '&nbsp;'
                    }
                }
            });

    </script>
@endsection