routes/web.php
<?php

use App\Helpers\Enums\UserRoleEnum;
use App\Http\Controllers\LanguageController;
use App\Models\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//  HOME ================================
Route::namespace('Front')->group(function (){
    Route::get('/auth/qrcode/{user:username}','QRCodeController@login')->name('auth.qrcode');
    Route::get('/auth/blocked/{user:username}','QRCodeController@blocked')->name('auth.blocked')->middleware(['auth']);
    Route::get('/check/certificate/{user:username}',function (User $user){})->name('check.certificate');
    Route::as('home.')->group(function (){

        Route::view('/', 'front.page.index')->name('index');
        Route::get('news','NewsController@index')->name('news.index');
        Route::get('news/{news:alias}','NewsController@show')->name('news.show');
        Route::get('decree','DecreeController@index')->name('decree.index');
        Route::get('decree/{decree:alias}','DecreeController@show')->name('decree.show');
        Route::get('certificate','CertificateController@index')->name('certificate.index');
        Route::post('certificate','CertificateController@search')->name('certificate.search');
        Route::get('certificate/{user:username}/download', 'CertificateController@download')->name('certificate.download');

        Route::prefix('vacancy')->as('vacancy.')->group(function (){
            Route::get('/','VacancyController@index')->name('index');
            Route::get('/{section:alias}','VacancyController@group')->name('group');
            Route::get('/{section:alias}/{vacancy:alias}','VacancyController@show')->name('show');
            Route::post('/{section:alias}/{vacancy:alias}','VacancyController@application')->name('application');
        });


    });
});

//  AUTH ================================
Auth::routes(['verify' => false]);

//  DASHBOARD ================================
Route::prefix('dashboard')
    ->namespace('Dashboard')
    ->as('dashboard.')
    ->middleware(['auth','role:'.UserRoleEnum::SUPER.'|'.UserRoleEnum::ADMIN.'|'.UserRoleEnum::MODERATOR])
    ->group(function (){
        Route::get('/','DashboardController@index')->name('index');

        //    News ======================================================================================
        Route::resource('news','NewsController')->except('show')->parameters(['news' => 'news:alias']);
        //    Decree ======================================================================================
        Route::resource('decree','DecreeController')->except('show')->parameters(['decree' => 'decree:alias']);
        //    Vacancy ======================================================================================
        Route::resource('vacancy','VacancyController')->parameters(['vacancy' => 'vacancy:alias']);

        Route::get('application','DashboardController@index')->name('vacancy.application');

        Route::prefix('group')->namespace('Group')->as('group.')->group(function (){
            Route::get("/",'GroupController@index')->name('index');

            Route::resource('section','SectionController')->except('show','edit','create');
            Route::resource('department','DepartmentController')->except('show','edit','create');
            Route::resource('position','PositionController')->except('show','edit','create');
        });

        Route::get('certificate','CertificateController@index')->name('certificate.index');
        Route::get('certificate/template','CertificateController@index')->name('certificate.template');

        Route::get('activity','DashboardController@index')->name('activity');
        Route::get('archive','DashboardController@index')->name('archive');

        Route::prefix('/staff')->namespace('Staff')->as('staff.')->group(function(){
            Route::get('/','StaffController@index')->name('index');
            Route::get('table','StaffController@table')->name('table');
            Route::get('excel','StaffController@exportExcel')->name('excel');
            Route::get('control','StaffController@control')->name('control');
            Route::get('create','ProfileController@create')->name('create');
            Route::post('create','ProfileController@store')->name('store');

            Route::prefix('{user:username}')->group(function (){
                Route::get('/','ProfileController@index')->name('profile.index');
                Route::delete('/','ProfileController@destroy')->name('profile.destroy');

                Route::put('profile','ProfileController@update')->name('profile.update');
                Route::put('profile/password/new', 'ProfileController@changePassword')->name('profile.password.new');
                Route::put('profile/password.reset', 'ProfileController@resetPassword')->name('profile.password.reset');

                Route::get('information','InformationController@index')->name('information.index');
                Route::post('information','InformationController@store')->name('information.store');
                Route::put('information','InformationController@update')->name('information.update');
                Route::delete('information','InformationController@destroy')->name('information.destroy');

                Route::get('education','EducationController@index')->name('education.index');
                Route::post('education','EducationController@store')->name('education.store');
                Route::put('education','EducationController@update')->name('education.update');
                Route::delete('education','EducationController@destroy')->name('education.destroy');

                Route::post('education/finished','EducationFinishedController@store')->name('education.finished.store');
                Route::put('education/finished/{finished}','EducationFinishedController@update')->name('education.finished.update');
                Route::delete('education/finished/{finished}','EducationFinishedController@destroy')->name('education.finished.destroy');

                Route::get('labor','LaborController@index')->name('labor.index');
                Route::post('labor','LaborController@store')->name('labor.store');
                Route::put('labor','LaborController@update')->name('labor.update');
                Route::delete('labor','LaborController@destroy')->name('labor.destroy');

                Route::get('work','WorkController@index')->name('work.index');
                Route::post('work','WorkController@store')->name('work.store');
                Route::put('work/{work}','WorkController@update')->name('work.update');
                Route::delete('work/{work}','WorkController@destroy')->name('work.destroy');

                Route::get('vacation','VacationController@index')->name('vacation.index');
                Route::post('vacation','VacationController@store')->name('vacation.store');
                Route::put('vacation/{vacation}','VacationController@update')->name('vacation.update');
                Route::delete('vacation/{vacation}','VacationController@destroy')->name('vacation.destroy');

                Route::get('family','FamilyController@index')->name('family.index');
                Route::post('family','FamilyController@store')->name('family.store');
                Route::put('family/{family}','FamilyController@update')->name('family.update');
                Route::delete('family/{family}','FamilyController@destroy')->name('family.destroy');

                Route::get('file','FileController@index')->name('file.index');
                Route::post('file','FileController@store')->name('file.store');
                Route::put('file','FileController@update')->name('file.update');
                Route::delete('file','FileController@destroy')->name('file.destroy');

                Route::get('reference', 'StaffController@reference')->name('reference');
                Route::get('certificate', 'StaffController@certificate')->name('certificate');
            });
        });
});

Route::prefix('staff-dashboard')
    ->namespace('StaffDashboard')
    ->as('staff-dashboard.')
    ->middleware(['auth','role:'.UserRoleEnum::STAFF])
    ->group(function (){
        Route::get('/','StaffDashboardController@index')->name('index');
        Route::get('reference', 'StaffController@reference')->name('staff.reference');
        Route::get('certificate', 'StaffController@certificate')->name('staff.certificate');

        Route::prefix('/pagination')->as('staff.')->namespace('Pagination')->group(function (){
            Route::get('profile','ProfileController@index')->name('profile.index');

            Route::put('profile','ProfileController@update')->name('profile.update');
            Route::put('profile/password/new', 'ProfileController@changePassword')->name('profile.password.new');

            Route::get('information','InformationController@index')->name('information.index');
            Route::post('information','InformationController@store')->name('information.store');
            Route::put('information','InformationController@update')->name('information.update');

            Route::get('education','EducationController@index')->name('education.index');
            Route::post('education','EducationController@store')->name('education.store');
            Route::put('education','EducationController@update')->name('education.update');

            Route::post('education/finished','EducationFinishedController@store')->name('education.finished.store');
            Route::put('education/finished/{finished}','EducationFinishedController@update')->name('education.finished.update');

app/Models/Vacancy.php
<?php

namespace App\Models;

use App\Helpers\Traits\HasCreator;
use App\Helpers\Traits\HasUpdater;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Collection;

/**
 * App\Models\vacancy
 *
 * @property int $id
 * @property string $title
 * @property string $alias
 * @property string|null $responsibility
 * @property string $requirement
 * @property string|null $skill
 * @property string|null $personal_quality
 * @property string|null $content
 * @property int $position_id
 * @property int $created_by
 * @property int $updated_by
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \App\Models\User $creator
 * @property-read \App\Models\Position $position
 * @property-read \App\Models\User $updater
 * @method static \Illuminate\Database\Eloquent\Builder|Vacancy newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Vacancy newQuery()
 * @method static \Illuminate\Database\Query\Builder|Vacancy onlyTrashed()
 * @method static \Illuminate\Database\Eloquent\Builder|Vacancy query()
 * @method static \Illuminate\Database\Eloquent\Builder|Vacancy whereAlias($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Vacancy whereContent($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Vacancy whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Vacancy whereCreatedBy($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Vacancy whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Vacancy wherePersonalQuality($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Vacancy wherePositionId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Vacancy whereRequirement($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Vacancy whereResponsibility($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Vacancy whereSkill($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Vacancy whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Vacancy whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Vacancy whereUpdatedBy($value)
 * @method static \Illuminate\Database\Query\Builder|Vacancy withTrashed()
 * @method static \Illuminate\Database\Query\Builder|Vacancy withoutTrashed()
 * @mixin \Eloquent
 */
class Vacancy extends Model
{
    use HasCreator,HasUpdater;

    protected $fillable = ['title','alias','content','responsibility','requirement','skill','personal_quality','position_id','created_by','updated_by'];


    public function position(): BelongsTo
    {
        return $this->belongsTo(Position::class);
    }

    public static function getBySection(int $section_id): Collection
    {
        $vacancies = self::all();
        $collection = collect();

        foreach ($vacancies as $vacancy){
            if ($vacancy->position->department->section->id === $section_id)
                $collection->push($vacancy);
        }
        return $collection;
    }

    public function application(): HasMany
    {
        return $this->hasMany(VacancyApplication::class);
    }
}

app/Http/Controllers/Dashboard/VacancyController.php
<?php


namespace App\Http\Controllers\Dashboard;

use App\Actions\Vacancy\CreateVacancyAction;
use App\Actions\Vacancy\UpdateVacancyAction;
use App\DTO\VacancyDTO;
use App\Http\Requests\Dashboard\Blog\VacancyRequest;
use App\Models\Position;
use App\Models\Vacancy;
use Exception;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Str;

class VacancyController extends BaseController
{


    public function index(){
        $breadcrumbs = [
            ['link' => route('dashboard.index'), 'name' => "<i class='feather icon-home'></i>"],
            ['name' => __('page.dashboard.blog.vacancy.index')]
        ];
        $vacancy = Vacancy::query()->latest()->get();
        return view('dashboard.page.vacancy.index',compact('breadcrumbs','vacancy'));
    }

    public function create(){
        $breadcrumbs = [
            ['link' => route('dashboard.index'), 'name' => "<i class='feather icon-home'></i>"],
            ['link' => route('dashboard.vacancy.index') ,'name' => __('page.dashboard.blog.vacancy.index')],
            ['name' => __('page.dashboard.blog.vacancy.create')]
        ];
        $positions = Position::all();
        return view('dashboard.page.vacancy.create',compact('positions','breadcrumbs'));
    }

    public function edit(Vacancy $vacancy){
        $breadcrumbs = [
            ['link' => route('dashboard.index'), 'name' => "<i class='feather icon-home'></i>"],
            ['link' => route('dashboard.vacancy.index') ,'name' => __('page.dashboard.blog.vacancy.index')],
            ['name' =>  Str::limit($vacancy->alias,80)]
        ];
        $positions = Position::all();
        return view('dashboard.page.vacancy.edit',compact('positions','breadcrumbs','vacancy'));
    }

    public function store(VacancyRequest $request, CreateVacancyAction $createVacancyAction): RedirectResponse
    {
        try {
            $vacancy = $createVacancyAction->execute(VacancyDTO::fromRequest($request));
            alert()->success(__('pages.blog.vacancy.success'));
            return redirect()->route('dashboard.vacancy.edit',['vacancy' => $vacancy->alias]);
        }catch (Exception $exception){
            alert()->error(__('pages.blog.vacancy.error'));
            return back();
        }
    }

    public function update(VacancyRequest $request, Vacancy $vacancy,UpdateVacancyAction $updateVacancyAction): RedirectResponse
    {
        try {
            $vacancy = $updateVacancyAction->execute(VacancyDTO::fromRequest($request,VacancyDTO::UPDATING),$vacancy);
            alert()->success(__('pages.blog.vacancy.success'));
            return redirect()->route('dashboard.vacancy.edit',['vacancy' => $vacancy->alias]);
        }catch (Exception $exception){
            alert()->error(__('pages.blog.vacancy.error'));
            return back();
        }
    }

    public function destroy(Vacancy $vacancy): JsonResponse
    {
        try {
            $vacancy->delete();
            return response()->json([
                'message' => __('message.decree.deleted'),
                'status' => true
            ]);
        } catch (Exception $e) {
            return response()->json([
                'message' => $e->getMessage(),
                'status' => false
            ],$e->getCode());
        }
    }
}

app/Http/Controllers/Front/VacancyController.php
<?php


namespace App\Http\Controllers\Front;


use App\Http\Requests\VacancyApplicationRequest;
use App\Models\Section;
use App\Models\Vacancy;

class VacancyController extends BaseFrontController
{

    public function index(){
        $sections = Section::all()->take(3);
        return view('front.page.vacancy.index',compact('sections'));
    }

    public function group(Section $section){
        $vacancies = Vacancy::getBySection($section->id);
        return view('front.page.vacancy.group',compact('vacancies','section'));
    }

    public function show($section,Vacancy $vacancy){
        $section = Section::where('alias',$section)->first();
        $breadcrumbs = [
            ['link' => route('home.index'), 'name' => "<i class='feather icon-home'></i>"],
            ['link'=> route('home.vacancy.index'),'name' => __('page.dashboard.blog.vacancy.index')],
            ['link'=> route('home.vacancy.group',['section' => $section->alias]),'name' => $section->title],
            ['name' => \Str::of($vacancy->title)->limit()],
        ];

        return view('front.page.vacancy.show',compact('breadcrumbs','section','vacancy'));
    }

    public function application(VacancyApplicationRequest $request){

    }

}

resources/views/dashboard/page/vacancy/index.blade.php
@extends('dashboard.layouts.dashboard')

@section('title', __('page.dashboard.blog.news.index'))

@section('vendor-style')
    {{-- Page Css files --}}
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/dataTables.bootstrap4.min.css')) }}">
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/responsive.bootstrap4.min.css')) }}">
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/buttons.bootstrap4.min.css')) }}">
@endsection

@section('page-style')
    {{-- Page Css files --}}
    <link rel="stylesheet" href="{{ asset(mix('css/base/plugins/forms/form-validation.css')) }}">
    <link rel="stylesheet" href="{{ asset(mix('css/base/pages/app-user.css')) }}">
    <style>
        @media (max-width: 576px) {
            .modal-slide-in.show .modal-dialog,
            .modal-slide-in .modal.show .modal-dialog{
                width: 100%!important;
            }
        }

        @media (min-width: 576px) and (max-width: 768px) {
            .modal-slide-in.show .modal-dialog,
            .modal-slide-in .modal.show .modal-dialog{
                width: 100%!important;
            }
        }
        .modal-backdrop{
            background-color: #ffffff!important;
        }
        .modal-backdrop.show{
            opacity: 0.8!important;
        }
    </style>
@endsection

@section('content')
    <!-- users list start -->
    <section class="app-user-list">
        <!-- list section start -->
        <div class="card">
            <div class="card-body">
                <div class="card-content">
                    <div class="card-datatable table-responsive pt-0">
                        <table class="user-list-table table">
                            <thead class="thead-light">
                            <tr>
                                <th></th>
                                <th>{{ __('dashboard.news_field.title') }}</th>
                                <th>На {{ __('dashboard.position') }}</th>
                                <th>{{ __('page.dashboard.blog.vacancy.application') }}</th>
                                <th>{{ __('dashboard.news_field.created_at') }}</th>
                                <th>{{ __('dashboard.action.title') }}</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($vacancy as $one)
                                <tr>
                                    <td></td>
                                    <td>
                                        {{ $one->title }}
                                    </td>
                                    <td>
                                        {{ $one->position->title }}
                                    </td>
                                    <td>
                                        {{ $one->application->count() }}
                                    </td>
                                    <td>
                                        <i class="feather icon-calendar"></i> {{ $one->created_at->format('H:i d.m.Y') }}
                                    </td>
                                    <td class="text-center">
                                        <a href="{{ route('dashboard.vacancy.edit',['vacancy' => $one->alias]) }}"><i class="feather icon-edit"></i></a>
                                        <button type="button" class="btn btn-link text-danger" onclick="deleteVacancy('{{ route('dashboard.vacancy.destroy', ['vacancy' => $one->alias]) }}')">
                                            <i class="feather icon-trash"></i>
                                        </button>
                                    </td>
                                </tr>
                            @empty
                            @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- list section end -->
    </section>
    <!-- users list ends -->
@endsection

@section('vendor-script')
    {{-- Vendor js files --}}
    <script src="{{ asset(mix('vendors/js/tables/datatable/jquery.dataTables.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.bootstrap4.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/dataTables.responsive.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/responsive.bootstrap4.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.buttons.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.bootstrap4.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/forms/validation/jquery.validate.min.js')) }}"></script>
    <script src="{{ asset('vendor/axios/axios.min.js') }}"></script>
@endsection

@section('page-script')
    <script>
        let dt_responsive_table = $('.user-list-table')
        let dt_responsive = dt_responsive_table.DataTable({
            pageLength: 10,
            aLengthMenu: [[5, 10, 15, 20], [5, 10, 15, 20]],
            columnDefs: [
                {
                    className: 'control',
                    orderable: false,
                    targets: 0
                },
            ],
            buttons: [
                {
                    text: '<i class="feather icon-plus-circle"></i> {{ __('dashboard.action.add') }}',
                    className: 'btn btn-primary mt-50',
                    attr: {
                        'onclick': 'createDecreeRoute()'
                    },
                    init: function (api, node, config) {
                        $(node).removeClass('btn-secondary');
                    }
                }
            ],
            dom:
                '<"d-flex justify-content-between align-items-center header-actions mx-1 row mt-75"' +
                '<"col-lg-12 col-xl-6" l>' +
                '<"col-lg-12 col-xl-6 pl-xl-75 pl-0"<"dt-action-buttons text-xl-right text-lg-left text-md-right text-left d-flex align-items-center justify-content-lg-end align-items-center flex-sm-nowrap flex-wrap mr-1"<"mr-1"f>B>>' +
                '>t' +
                '<"d-flex justify-content-between mx-2 row mb-1"' +
                '<"col-sm-12 col-md-6"i>' +
                '<"col-sm-12 col-md-6"p>' +
                '>',
            language: {
                "decimal":        "",
                "emptyTable":     "Нет данных в таблице",
                "info":           "Показано с _START_ по _END_ из _TOTAL_ записей",
                "infoEmpty":      "Показано с 0 по 0 из 0 записей",
                "infoFiltered":   "(отфильтровано из _MAX_ записей)",
                "infoPostFix":    "",
                "thousands":      ",",
                "lengthMenu":     "Показать _MENU_ записей",
                "loadingRecords": "Загрузка...",
                "processing":     "Обработка...",
                "search":         "Поиск:",
                "zeroRecords":    "Сотрудник не найден",
                "paginate": {
                    "first":      "Первый",
                    "last":       "Последний",
                    previous: '&nbsp;',
                    next: '&nbsp;'
                }
            }
        });
        function deleteVacancy(route){
            Swal.fire({
                title: '{{ __('message.are_you_sure') }}',
                text: '{{ __('message.dont_revert') }}',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: '{{ __('message.yes_delete') }}',
                cancelButtonText: '{{ __('message.cancel') }}',
                customClass: {
                    confirmButton: 'btn btn-primary',
                    cancelButton: 'btn btn-outline-danger ml-1'
                },
                buttonsStyling: false
            }).then(function (result) {
                if (result.value) {
                    axios.delete(route).then(response => {
                        if (response.data.status){
                            Swal.fire({
                                title: response.data.message,
                                text: '',
                                icon: 'success',
                                showCancelButton: false,
                                confirmButtonText: 'Ok',
                                customClass: {
                                    confirmButton: 'btn btn-primary',
                                },
                                buttonsStyling: false
                            }).then(function (result){
                                window.location.reload()
                            });
                        }
                    }).catch(response => {
                        Swal.fire({
                            icon: 'error',
                            title: '{{ __('message.deleted') }}',
                            customClass: {
                                confirmButton: 'btn btn-success'
                            }
                        });
                    })

                }
            });
        }
        function createVacancyRoute(){
            window.location.href = '{{ route('dashboard.vacancy.create') }}'
        }
    </script>
@endsection